### ISSUE TITLE
Can't read BAM file

### ISSUE THREAD

**Issue by dcizin** [biocore-ntnu/pyranges#211]
```
>>> import pyranges as pr
>>> bam = pr.read_bam('my_bam_file.bam')                                                                                           
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/name/anaconda3/envs/kal/lib/python3.6/site-packages/pyranges/readers.py", line 189, in read_bam
    if bamread.__version__ in ["0.0.1", "0.0.2", "0.0.3", "0.0.4",
AttributeError: module 'bamread' has no attribute '__version__'
```

bamread was installed via "conda install -c bioconda bamread", is version 0.0.9, and works independently of pyranges:
```
>>> import bamread
>>> bam = bamread.read_bam('my_bam_file.bam')                                                                                           
>>> bam
       Chromosome     Start       End Strand  Flag
0            chr1     14494     14584      -    16
1            chr1     14494     14584      -    16
2            chr1     14563     14653      -    16
3            chr1     14566     14656      -    16
4            chr1     14602     14692      -    16
...           ...       ...       ...    ...   ...
251970       chrY  11190180  11190240      +     0
251971       chrY  11190180  11190240      +     0
251972       chrY  11191818  11191908      -    16
251973       chrY  11192535  11192625      -    16
251974       chrY  11212708  11212798      -    16

[251975 rows x 5 columns]
```

**Comment by endrebak** [comment]
Fixed in bamread 0.0.10 which is out now. Newer versions of pyranges will require it. Thanks :)
